name: Symfony CI Pipeline

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  symfony-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Adapter si nécessaire
          extensions: mbstring, intl, pdo_pgsql
          tools: symfony, phpstan, phpunit

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: "${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set environment for testing
        run: |
          cp .env .env.local
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --force --env=test
        env:
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/criti-pixel?serverVersion=16&charset=utf8"

      - name: Load Fixtures
        run: php bin/console doctrine:fixtures:load --group=test -n --purge-with-truncate
        env:
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/criti-pixel_test?serverVersion=16&charset=utf8"

      - name: Run PHPUnit tests
        run: php bin/phpunit
        env:
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/criti-pixel_test?serverVersion=16&charset=utf8"

      - name: Run PHPStan
        run: phpstan analyse src --level=6